import type { CreateScheduleInput } from "./types.ts";

export const DEFAULT_SCHEDULES: CreateScheduleInput[] = [
  {
    name: "haunt",
    type: "builtin",
    command: "haunt",
    intervalMs: 1_800_000,
    timeoutMs: 600_000,
    enabled: false,
  },
  {
    name: "distill",
    type: "builtin",
    command: "distill",
    intervalMs: 7_200_000,
    timeoutMs: 1_800_000,
    enabled: true,
  },
  {
    name: "stoke",
    type: "builtin",
    command: "skills stoke",
    intervalMs: 86_400_000,
    timeoutMs: 300_000,
    enabled: true,
  },
  {
    name: "attune",
    type: "builtin",
    command: "souls attune",
    intervalMs: 300_000,
    timeoutMs: 240_000,
    enabled: true,
  },
  {
    name: "trail_sweep",
    type: "builtin",
    command: "trail sweep",
    intervalMs: 86_400_000,
    timeoutMs: 600_000,
    enabled: true,
  },
  {
    name: "prowl",
    type: "builtin",
    command: "quests prowl",
    intervalMs: 60_000,
    timeoutMs: 30_000,
    enabled: false,
  },
  {
    name: "tend",
    type: "builtin",
    command: "quests tend",
    intervalMs: 1_800_000,
    timeoutMs: 60_000,
    enabled: false,
  },
];
